apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-busybox
spec:
  replicas: 2
  selector:
    name: nfs-busybox
  template:
    metadata:
      labels:
        name: nfs-busybox
    spec:
      containers:
        - image: busybox
          command:
            - sh
            - -c
            - "while true; do sleep $(($RANDOM % 5 + 5)); done"
          imagePullPolicy: IfNotPresent
          name: busybox
          volumeMounts:
            - name: nfs-1
              mountPath: "/mnt/tram-1"
            - name: nfs-2
              mountPath: "/mnt/tram-2"
            - name: nfs-3
              mountPath: "/mnt/tram-3"
      volumes:
        - name: nfs-1
          persistentVolumeClaim:
            claimName: nfs-1
        - name: nfs-2
          persistentVolumeClaim:
            claimName: nfs-2
        - name: nfs-3
          persistentVolumeClaim:
            claimName: nfs-3
