kind: ConfigMap
apiVersion: v1
metadata:
  name: nfs-server-cm
data:
  exports: |
    /exports *(rw,fsid=0,insecure,no_root_squash)
    / *(rw,fsid=0,insecure,no_root_squash)
    /data/* *(rw,fsid=0,insecure,no_root_squash)