apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-3
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.nfs.svc.cluster.local
    path: "/data3"
  mountOptions:
    - nfsvers=4.2
